config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :highscores
  resources :users
get "log_out" => "sessions#destroy", :as => "log_out"
get "log_in" => "sessions#new", :as => "log_in"
get "sign_up" => "users#new", :as => "sign_up"
root :to => "pages#show"
put 'generics/:score' => "generics#new"
resources :users
resources :sessions
end

app/models/highscore.rb
# == Schema Information
#
# Table name: highscores
#
#  id         :integer          not null, primary key
#  score      :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  highscore  :string
#  name       :string
#

class Highscore < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string
#  password_digest :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  has_many :highscores
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 helper_method :current_user

private

def current_user
  @current_user ||= User.find_by(:id => session[:user_id]) if session[:user_id]
end
  protect_from_forgery with: :exception
end

app/controllers/generics_controller.rb
    
class GenericsController < ApplicationController
  def new
    @user = User.create(name: "New User", password: "chicken", password_confirmation: "chicken")
    session[:user_id] = @user.id
    @highscore = Highscore.create(user_id: @user.id.to_i, score: params['score'])
    session[:highscore] = @highscore
    respond_to do |format|
      format.html { render 'users/edit' }
      format.json { render :json => { status: "200 OK" }}
    end
  end
end

app/controllers/highscores_controller.rb
class HighscoresController < ApplicationController
  before_action :set_highscore, only: [:show, :edit, :update, :destroy]

  # GET /highscores
  # GET /highscores.json
  def index
    @highscores = Highscore.all
  end

  # GET /highscores/1
  # GET /highscores/1.json
  def show
  end

  # GET /highscores/new
  def new
    @highscore = Highscore.new
  end

  # GET /highscores/1/edit
  def edit
  end

  # POST /highscores
  # POST /highscores.json
  def create
    # @highscore = Highscore.new(highscore_params)
    @highscore = Highscore.find_by :user_id => params[:highscore][:user_id] 
    if @highscore.nil?
      @highscore = Highscore.new(highscore_params) 
    else
      @highscore.update highscore_params
    end

    respond_to do |format|
      if @highscore.save
        format.html { redirect_to @highscore, notice: 'Highscore was successfully created.' }
        format.json { render :show, status: :created, location: @highscore }
      else
        format.html { render :new }
        format.json { render json: @highscore.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /highscores/1
  # PATCH/PUT /highscores/1.json
  def update
    respond_to do |format|
      if @highscore.update(highscore_params)
        format.html { redirect_to @highscore, notice: 'Highscore was successfully updated.' }
        format.json { render :show, status: :ok, location: @highscore }
      else
        format.html { render :edit }
        format.json { render json: @highscore.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /highscores/1
  # DELETE /highscores/1.json
  def destroy
    @highscore.destroy
    respond_to do |format|
      format.html { redirect_to highscores_url, notice: 'Highscore was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_highscore
      @highscore = Highscore.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def highscore_params
      params.require(:highscore).permit(:score, :user_id, :name)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
end

def create
  user = User.find_by(:name => params[:name]).authenticate( params[:password] )
  if user
    session[:user_id] = user.id
    redirect_to user_path(user)
  else
    flash.now.alert = "Invalid name or password"
    render "new"
  end
end

def destroy
  session[:user_id] = nil
  redirect_to root_url, :notice => "Logged out!"
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @users = User.all
  end

  # GET /users/new
  def new
    @user = User.find_by( :id => session[:user_id] ) || User.new
  end


  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.find_by( :id => session[:user_id] ) || User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation,:user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/highscores_helper.rb
module HighscoresHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/generics/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.text_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/highscores/_form.html.erb
<%= form_for(@highscore) do |f| %>
  <% if @highscore.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@highscore.errors.count, "error") %> prohibited this highscore from being saved:</h2>

      <ul>
      <% @highscore.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :score %><br>
    <%= f.number_field :score %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/highscores/edit.html.erb
<h1>Editing Highscore</h1>

<%= render 'form' %>

<%= link_to 'Show', @highscore %> |
<%= link_to 'Back', highscores_path %>

app/views/highscores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Highscores</h1>

<table>
  <thead>
    <tr>
      <th>Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @highscores.each do |highscore| %>
      <tr>
        <td><%= highscore.score %></td>
        <td><%= link_to 'Show', highscore %></td>
        <td><%= link_to 'Edit', edit_highscore_path(highscore) %></td>
        <td><%= link_to 'Destroy', highscore, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Highscore', new_highscore_path %>

app/views/highscores/new.html.erb
<h1>New Highscore</h1>

<%= render 'form' %>

<%= link_to 'Back', highscores_path %>

app/views/highscores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Score:</strong>
  <%= @highscore.score %>
</p>

<%= link_to 'Edit', edit_highscore_path(@highscore) %> |
<%= link_to 'Back', highscores_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SpaceraceApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Orbitron:500' rel='stylesheet' type='text/css'>
</head>
<body>
<div id="container">
<div class="formContain">
<button type="button"  data-toggle="modal" data-target=".bs-example-modal-sm">Sign In</button>
  <div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <h1>Log in</h1>

<%= form_tag sessions_path do %>
  <p>
    <%= label_tag :name %><br />
    <%= text_field_tag :name, params[:name] %>
  </p>
  <p>
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </p>
  <p class="button"><%= submit_tag "Log in" %></p>
<% end %>
    </div>
  </div>
</div>

<div id="saveScore">
  <button type="button" id="myButton" data-loading-text="Loading..."  autocomplete="off">
  Save Score!
</button>

<script>
var app = app || {}

  var user_id = <%= current_user  ? current_user.id : "null" %>;
  $('#myButton').one('click', function () {

    $.ajax({
      url: "/highscores",
      method: "POST",
      dataType: "JSON",
      data: {
        highscore: {
          score: app.score,
          user_id: user_id
        }
      },
      success:function(data){
        console.log(data);
      }
    })
  })
</script>
</div>

<div>
<form action="/sign_up/" >

<button >Sign Up</button>
</form>
<script>
  var changePage = function (genericScore) {
    var newURL = "/sign_up";
    window.location = newURL;
  };

  $('#container > div.formContain > div:nth-child(4) > form > button').on('click', function(event){
    event.preventDefault()
    $.ajax({
      url: "/generics/" +app.score,
      method: "PUT",
      dataType: "JSON",
      success: function(data){
        changePage( app.score ); 
      }
    })
  })
</script>
</div>
<!-- omg -->


<div id="user_nav">
  <% if current_user %>
    <%= link_to "Log out", log_out_path %>
    <% end %>
    <% if current_user %>
    <%= current_user.name %>.
    <%= link_to "Stats", "users/#{current_user.id}" %>
    <% end %>
</div>

<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>
<%= yield %>
</div>
</div>
</body>
</html>

app/views/pages/show.html.erb
<html>

 <head>
  <meta charset="utf-8" />
 <title>Invaders</title>
 </head>
 <body>

 </body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field" type="password">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field" type="password">
    <%= f.label :password_confirmation %><br>
    <%= f.text_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>
<!-- commit -->

app/views/users/stats.html.erb
<h1> yo</h1>